# Generated by Django 4.2 on 2025-10-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='selected_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
